name: Diff modified views

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/views/**'
      - '.github/workflows/diff.yml'
  push:
    paths:
      - 'frontend/views/**'
      - '.github/workflows/diff.yml'

jobs:
  diff:
    uses: Smithsonian/caas-aspace-services/.github/workflows/diff.yml@main
    with:
      prod_archivesspace_version: v4.1.0
